server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petscare_auth?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

# CORS y seguridad: normalmente en dev permitimos todo
app:
  cors:
    allowed-origins: "*"
