server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petscare_auth?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true  

app:
  cors:
    allowed-origins: "*"
