server:
  port: ${PORT:8080}

spring:
  datasource:
    # DB_URL debe ser una JDBC válida (ej: jdbc:mysql://HOST:PORT/DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC)
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
